version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - ECR_REPOSITORY_URI="$(aws ecr --region $AWS_REGION describe-repositories --query "repositories[?repositoryName=='hello-world-python-docker'].repositoryUri" --output=text)"
      - IMAGE_URI="${ECR_REPOSITORY_URI}:latest"
      - echo "IMAGE_URI=${IMAGE_URI}"
      - echo "LATEST=${ECR_REPOSITORY_URI}:latest"
  build:
    commands:
      - echo "Building docker image"
      - docker build -t "$IMAGE_URI" .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push "$IMAGE_URI"
      - printf '[{"name":"hello-world-python-docker","imageUri":"%s"}]' "$IMAGE_URI" > images.json

artifacts:
  files: images.json

